name = "example"
uuid = "f2cbfeaa-21ae-4cf8-8768-08347d117519"
authors = ["Johannes Blaschke <jpblaschke@lbl.gov>"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
MPI = "0.20.22"
